# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xZbMZVrtX80rEdJHFRfXgOu9SV2AP7_3
"""

import pandas as pd

data = {
    "id":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "nome":[
        'Josefino Pinto','Lucas Lira','Júlio Cocielo','Felipe Rocha','Gabriela Farias','Henrique Dias','Isabela Torres',
        'Dalton Luz','João Alves','Marina Lopes','Lucas Mendes','Marina Castro','Nicolas Araújo','Thalys Nogueira','Felipe Smith',
    ],
    "idade":[15,17,15,16,17,15,16,17,15,16,17,15,16,17,15],
    "nota_p1":[9.5,4.5,8,10,9.5,4.5,8,10,9.5,4.5,8,10,9.5,4.5,8],
    "nota_p2":[8,10,2.3,8,7.1,6.3,8.5,9.1,5.1,2.5,3.4,1.1,8,6.7,5.3],
    "nota_p3":[6,9,6,7,10,8.1,6.3,5.5,4.1,3.3,1.1,2.9,3.8,4.1,10],
    "faltas":[1,8,0,9,11,21,9,10,3,12,9,1,3,11,9],
}

mainframe = pd.DataFrame(data)

mainframe

def classificar(row):
  if row["media_final"] >= 6 and row["faltas"] <= 10:
    return "aprovado"
  elif row["media_final"] > 6 and row["faltas"] > 10:
    return "reprovado por faltas"
  else:
    return "reprovado por nota"

mainframe["media_final"] = round((mainframe["nota_p1"] + mainframe["nota_p2"] + mainframe["nota_p3"]) / 3)

mainframe["media_final"] = round((mainframe["nota_p1"] + mainframe["nota_p2"] + mainframe["nota_p3"]) / 3)
print(f"média: {round(mainframe['media_final'].mean(), 2)}")
print(f"mediana: {round(mainframe['media_final'].median(), 2)}")
print(f"moda: {round(mainframe['media_final'].mode(), 2)}")
print(mainframe["media_final"].describe())

mainframe

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Randomize grades for better distribution
for col in ['nota_p1', 'nota_p2', 'nota_p3']:
    # Add random noise between -1 and 1, then clip to ensure grades are between 0 and 10
    mainframe[f'{col}_rand'] = np.clip(mainframe[col] + np.random.uniform(-1, 1, size=len(mainframe)), 0, 10)

# Recalculate media_final with randomized grades
mainframe['media_final_rand'] = round((mainframe['nota_p1_rand'] + mainframe['nota_p2_rand'] + mainframe['nota_p3_rand']) / 3)

# Plot the distribution of the randomized final media
plt.figure(figsize=(10, 6))
sns.histplot(mainframe['media_final_rand'], kde=True, bins=range(int(mainframe['media_final_rand'].min()), int(mainframe['media_final_rand'].max()) + 2))
plt.title('Distribuição da Média Final (Notas)')
plt.xlabel('Média Final')
plt.ylabel('Frequência')
plt.xticks(range(int(mainframe['media_final_rand'].min()), int(mainframe['media_final_rand'].max()) + 2))
plt.grid(axis='y', alpha=0.75)
plt.show()



